-- Make the About and Contact pages editable from the CMS.
--
-- Both pages were rebuilt with their copy written directly into the templates,
-- which meant none of it could be changed without editing PHP. This moves every
-- string into page_blocks so it appears under Content -> Page copy, and drops the
-- twelve orphaned About blocks left by the old template.

DELETE FROM `page_blocks` WHERE `page_key` = 'about';
DELETE FROM `page_blocks` WHERE `page_key` = 'contact' AND `block_key` IN ('heading', 'intro');

-- response_note predates this and sat in its own one-field group. It is the line
-- beside the submit button, so it belongs with the rest of the form.
UPDATE `page_blocks`
   SET `group_name` = 'Form', `label` = 'Note beside the button', `sort_order` = 14
 WHERE `page_key` = 'contact' AND `block_key` = 'response_note';

INSERT INTO `page_blocks` (`page_key`, `block_key`, `label`, `type`, `value`, `group_name`, `sort_order`) VALUES
('about', 'hero_eyebrow', 'Hero eyebrow', 'text', 'About · Subramanyam M N', 'Hero', 1),
('about', 'hero_heading', 'Hero heading', 'text', 'Strategy and creative, under one roof', 'Hero', 2),
('about', 'hero_lede', 'Hero intro', 'textarea', 'I''m a digital marketing strategist and content creator in Chennai — building brand strategy, ad creative, SEO and AI-assisted video for brands across South India.', 'Hero', 3),
('about', 'intro_label', 'Section label', 'text', 'More than just a content guy', 'Intro', 10),
('about', 'intro_heading', 'Heading', 'text', 'The thinking and the making, in one place', 'Intro', 11),
('about', 'intro_body', 'Body', 'html', '<p>I work across the parts of marketing most people split into separate hires — brand and media strategy, advertising creative, SEO and video production. I handle both the thinking and the making, for a handful of clients at a time.</p><p>Most brands hit the same wall: the strategy lives in one deck, the creative lives in another head, and the two never quite line up. I work end to end so they do — the plan and the thing you actually post come from the same place.</p><p>I work a lot in Tamil and South Indian advertising contexts, so the language, the cultural cues and the local consumer behaviour aren''t an afterthought — they''re built in from the first draft.</p>', 'Intro', 12),
('about', 'intro_cta_primary', 'Primary button label', 'text', 'Work with me', 'Intro', 13),
('about', 'intro_cta_primary_href', 'Primary button link', 'url', '/contact', 'Intro', 14),
('about', 'intro_cta_secondary', 'Secondary button label', 'text', 'See my services', 'Intro', 15),
('about', 'intro_cta_secondary_href', 'Secondary button link', 'url', '/services', 'Intro', 16),
('about', 'philosophy_label', 'Section label', 'text', 'My philosophy', 'Philosophy', 20),
('about', 'philosophy_heading', 'Heading', 'text', 'Evidence over elegance', 'Philosophy', 21),
('about', 'philosophy_body', 'Body', 'html', '<p>The rule I work by: if something sounds correct but doesn''t come from anything real or testable, I don''t trust it enough to pass it on to a client.</p><p>A lot of marketing advice is coherent, confident and wrong. It sounds right in a meeting and falls apart the moment it meets a real audience. So I anchor decisions in what''s actually been observed — what a video''s retention curve is doing, which hook held attention, which segment actually converted — instead of what looks good on a slide.</p>', 'Philosophy', 22),
('about', 'philosophy_card_1_title', 'Card 1 title', 'text', 'New & small brands', 'Philosophy', 23),
('about', 'philosophy_card_1_body', 'Card 1 body', 'textarea', 'You don''t have budget to waste on guesses. I keep things lean and test before scaling, so the money goes where there''s evidence it works.', 'Philosophy', 24),
('about', 'philosophy_card_2_title', 'Card 2 title', 'text', 'Established brands', 'Philosophy', 25),
('about', 'philosophy_card_2_body', 'Card 2 body', 'textarea', 'I plug into what you already have, read the existing data honestly — including the parts that aren''t flattering — and build from there.', 'Philosophy', 26),
('about', 'approach_label', 'Section label', 'text', 'How I work', 'Approach', 30),
('about', 'approach_heading', 'Heading', 'text', 'My approach', 'Approach', 31),
('about', 'approach_step_1_title', 'Step 1 title', 'text', 'Understand the brand before touching anything', 'Approach', 33),
('about', 'approach_step_1_body', 'Step 1 body', 'textarea', 'I don''t start with tactics. I start with what the brand actually is, who it''s really for, and where the current funnel leaks. Get that read wrong and every ad after it is wasted — often the real moat is community or trust, not the spec sheet.', 'Approach', 34),
('about', 'approach_step_2_title', 'Step 2 title', 'text', 'Creative that earns attention', 'Approach', 35),
('about', 'approach_step_2_body', 'Step 2 body', 'textarea', 'The creative is the targeting. I shoot and edit video — reels and long-form — and structure it around hooks, pacing and story, not just "make it look nice." I''ve built everything from UGC-style ads to a full cinematic brand film.', 'Approach', 36),
('about', 'approach_step_3_title', 'Step 3 title', 'text', 'Build for the local audience, in the local language', 'Approach', 37),
('about', 'approach_step_3_body', 'Step 3 body', 'textarea', 'Scripts and voiceovers in English, Tamil and Tanglish depending on who''s watching. A message that lands in Chennai isn''t the same one that lands nationally, and pretending otherwise is how good budgets get wasted.', 'Approach', 38),
('about', 'approach_step_4_title', 'Step 4 title', 'text', 'SEO and structure so the work compounds', 'Approach', 39),
('about', 'approach_step_4_body', 'Step 4 body', 'textarea', 'Ad spend stops the day you stop paying. Search and on-page structure keep working. I treat technical SEO, keyword strategy and content as the part of the funnel that builds equity over time.', 'Approach', 40),
('about', 'approach_step_5_title', 'Step 5 title', 'text', 'Show the work honestly', 'Approach', 41),
('about', 'approach_step_5_body', 'Step 5 body', 'textarea', 'If something isn''t working, I say so early instead of dressing it up. Correcting course fast is cheaper than defending a losing plan.', 'Approach', 42),
('about', 'creative_label', 'Section label', 'text', 'The creative advantage', 'Creative', 50),
('about', 'creative_heading', 'Heading', 'text', 'AI-assisted video, built on real editing', 'Creative', 51),
('about', 'creative_body', 'Body', 'html', '<p>I use AI-assisted video production, but on top of real hands-on editing — not as a replacement for knowing how a video is actually put together.</p><p>I shoot and cut entirely on the phone, reels and long-form both. That''s deliberate, not a limitation — it keeps the workflow fast, cheap and close to how the audience actually watches. Knowing how to hold a hook, pace a cut and structure a story is what makes the AI tooling useful instead of gimmicky. The tools speed up the boring parts; the judgement about what makes something watchable is still the work.</p>', 'Creative', 52),
('about', 'creative_highlight', 'Highlighted example', 'textarea', 'For Cobblestone Footwear, a Chennai footwear brand, I made a cinematic brand film — "Sample Brand Film" — regional-language dialogue, produced with AI video tools and documented end to end. Same brand, also UGC-style ads and a family brand film. The range matters: the right format depends on the goal, not on what I happen to be comfortable making.', 'Creative', 53),
('about', 'work_label', 'Section label', 'text', 'Track record', 'Track record', 60),
('about', 'work_heading', 'Heading', 'text', 'Work across different industries', 'Track record', 61),
('about', 'work_lede', 'Intro', 'textarea', 'I''ve worked across drones, packaging, footwear and automotive strategy — different enough that I''ve had to actually understand each business rather than run one playbook everywhere.', 'Track record', 62),
('about', 'client_1_name', 'Client 1 name', 'text', 'Acme Drones', 'Track record', 66),
('about', 'client_1_meta', 'Client 1 sector', 'text', 'My own FPV drone build service', 'Track record', 67),
('about', 'client_1_href', 'Client 1 link (optional)', 'url', 'https://example.com', 'Track record', 68),
('about', 'client_1_body', 'Client 1 description', 'textarea', 'A custom FPV drone build brand I run myself. Because it''s mine, it''s where I test everything first — including an AI content system that writes and publishes SEO blog posts straight into the site''s custom CMS. If an idea can''t survive on my own brand, I don''t sell it.', 'Track record', 69),
('about', 'client_2_name', 'Client 2 name', 'text', 'Northwind Packaging', 'Track record', 70),
('about', 'client_2_meta', 'Client 2 sector', 'text', 'Packaging manufacturer · Chennai', 'Track record', 71),
('about', 'client_2_href', 'Client 2 link (optional)', 'url', '', 'Track record', 72),
('about', 'client_2_body', 'Client 2 description', 'textarea', 'Recurring content for a B2B manufacturer — Instagram Reel packages for their flagship product (scripts, shot lists and voiceovers across English, Tamil and Tanglish), plus LinkedIn headlines and 3D packaging poster design. B2B doesn''t get a pass on good creative.', 'Track record', 73),
('about', 'client_3_name', 'Client 3 name', 'text', 'Cobblestone Footwear', 'Track record', 74),
('about', 'client_3_meta', 'Client 3 sector', 'text', 'Footwear brand · Chennai', 'Track record', 75),
('about', 'client_3_href', 'Client 3 link (optional)', 'url', '', 'Track record', 76),
('about', 'client_3_body', 'Client 3 description', 'textarea', 'Advertising creative including UGC-style ads and "Sample Brand Film" — a cinematic brand film in a regional language, produced with AI video tools and documented end to end.', 'Track record', 77),
('about', 'client_4_name', 'Client 4 name', 'text', 'Beacon Labs', 'Track record', 78),
('about', 'client_4_meta', 'Client 4 sector', 'text', 'Drone education', 'Track record', 79),
('about', 'client_4_href', 'Client 4 link (optional)', 'url', '', 'Track record', 80),
('about', 'client_4_body', 'Client 4 description', 'textarea', 'Training content for their drone education vertical — speaker scripts and branded presentation decks.', 'Track record', 81),
('about', 'work_footnote', 'Closing note', 'textarea', 'I''m also building my own agency practice — bringing this strategy-plus-creative approach under one roof instead of scattering it across freelancers.', 'Track record', 85),
('about', 'cred_label', 'Section label', 'text', 'Credentials', 'Credentials', 90),
('about', 'cred_heading', 'Heading', 'text', 'Skills I''ve actually validated', 'Credentials', 91),
('about', 'cred_intro', 'Intro', 'textarea', 'I''d rather show the work than list badges. But where I''ve formally trained, it''s training I use on real projects.', 'Credentials', 92),
('about', 'cred_1_title', 'Credential 1 title', 'text', 'SEO & WordPress', 'Credentials', 94),
('about', 'cred_1_body', 'Credential 1 body', 'textarea', 'A technical certification covering technical SEO, structured data, keyword strategy and hosting.', 'Credentials', 95),
('about', 'cred_2_title', 'Credential 2 title', 'text', 'AI-assisted content & video', 'Credentials', 96),
('about', 'cred_2_body', 'Credential 2 body', 'textarea', 'Prompt engineering and AI video production, used daily across client and personal projects.', 'Credentials', 97),
('about', 'cred_3_title', 'Credential 3 title', 'text', 'Video editing & production', 'Credentials', 98),
('about', 'cred_3_body', 'Credential 3 body', 'textarea', 'Hands-on shooting and editing, phone-first workflow.', 'Credentials', 99),
('about', 'journey_label', 'Section label', 'text', 'The journey', 'Journey', 110),
('about', 'journey_heading', 'Heading', 'text', 'How I got here', 'Journey', 111),
('about', 'journey_body', 'Body', 'html', '<p>I didn''t start with a fixed playbook — I built the approach by doing the work across very different clients and watching what held up. A drone brand, a packaging manufacturer and a footwear label don''t share a template. What they share is a method: understand the business first, ground every decision in something observable, and make the creative earn its place.</p><p>That''s also why I run my own brand, Acme Drones. It''s the one place I can test an idea with real money and real stakes before recommending it to anyone else. If it works there, I trust it. If it doesn''t, it doesn''t leave the lab.</p>', 'Journey', 112),
('about', 'journey_points', 'Pull-out points', 'html', '<ul><li>I don''t just "make content" — I build the strategy and the creative so they point the same direction.</li><li>I work natively in Tamil and South Indian contexts, which most national playbooks miss.</li></ul>', 'Journey', 113),
('about', 'faq_label', 'Section label', 'text', 'FAQ', 'FAQ', 120),
('about', 'faq_heading', 'Heading', 'text', 'Common questions', 'FAQ', 121),
('about', 'faq_1_q', 'Question 1', 'text', 'What exactly do you do — strategy, or content?', 'FAQ', 123),
('about', 'faq_1_a', 'Answer 1', 'textarea', 'Both, and that''s the point. I build the brand and media strategy and the creative that executes it, so nothing gets lost in the handoff between a strategist and a separate content team.', 'FAQ', 124),
('about', 'faq_2_q', 'Question 2', 'text', 'What makes your video work different?', 'FAQ', 125),
('about', 'faq_2_a', 'Answer 2', 'textarea', 'I use AI-assisted production, but built on real editing skill and a phone-first workflow. The tools speed things up; knowing how to hold attention is what makes them actually work. I shoot and cut across reels and long-form, in English, Tamil and Tanglish.', 'FAQ', 126),
('about', 'faq_3_q', 'Question 3', 'text', 'Do you only work with big brands?', 'FAQ', 127),
('about', 'faq_3_a', 'Answer 3', 'textarea', 'No. I keep a small client roster and work with both new brands on tight budgets and established ones. For smaller brands, the whole approach is testing before scaling so nothing gets wasted.', 'FAQ', 128),
('about', 'faq_4_q', 'Question 4', 'text', 'Can you handle work in Tamil / for a South Indian audience?', 'FAQ', 129),
('about', 'faq_4_a', 'Answer 4', 'textarea', 'Yes — that''s a core part of what I do, not a translation step bolted on at the end. Scripts, voiceovers and cultural cues are built for the local audience from the start.', 'FAQ', 130),
('about', 'cta_eyebrow', 'Eyebrow', 'text', 'Let''s work together', 'Closing CTA', 140),
('about', 'cta_heading', 'Heading', 'text', 'Strategy and creative from the same place', 'Closing CTA', 141),
('about', 'cta_lede', 'Body', 'textarea', 'If you want decisions grounded in what actually works rather than what sounds good on a deck — let''s talk.', 'Closing CTA', 142),
('about', 'cta_primary', 'Primary button label', 'text', 'Get in touch', 'Closing CTA', 143),
('about', 'cta_primary_href', 'Primary button link', 'url', '/contact', 'Closing CTA', 144),
('about', 'cta_secondary', 'Secondary button label', 'text', 'See all services', 'Closing CTA', 145),
('about', 'cta_secondary_href', 'Secondary button link', 'url', '/services', 'Closing CTA', 146),
('contact', 'hero_eyebrow', 'Hero eyebrow', 'text', 'Contact', 'Hero', 1),
('contact', 'hero_heading', 'Hero heading', 'text', 'Let''s have a straight conversation', 'Hero', 2),
('contact', 'hero_lede', 'Hero intro', 'textarea', 'Tell me where you''re trying to get to. I work with a small number of brands at a time, so I read every enquiry myself and reply within one business day.', 'Hero', 3),
('contact', 'form_label', 'Section label', 'text', 'Say hello', 'Form', 10),
('contact', 'form_heading', 'Heading', 'text', 'No pitch dressed up as a call', 'Form', 11),
('contact', 'form_intro', 'Intro', 'textarea', 'Fill in the form and tell me what you''re working on — what the brand is, where you feel stuck, and what "working" would look like for you. If I think I can help, I''ll say how. If I don''t, I''ll tell you that too and point you somewhere better.', 'Form', 12),
('contact', 'form_button', 'Submit button label', 'text', 'Send message', 'Form', 13),
('contact', 'details_label', 'Section label', 'text', 'Contact details', 'Details', 20),
('contact', 'details_intro', 'Intro', 'textarea', 'Prefer a direct line? Reach me on any of these.', 'Details', 21),
('contact', 'next_label', 'Section label', 'text', 'What happens next', 'Next', 30),
('contact', 'next_heading', 'Heading', 'text', 'From first message to live work', 'Next', 31),
('contact', 'next_lede', 'Intro', 'textarea', 'I''d rather you know exactly how this goes than wonder. Here''s the actual sequence.', 'Next', 32),
('contact', 'step_1_title', 'Step 1 title', 'text', 'We talk, no obligation', 'Next', 34),
('contact', 'step_1_body', 'Step 1 body', 'textarea', 'A short call or exchange to understand the business, not to sell you anything. I want to know who your real buyer is, what you''ve already tried, and where the funnel leaks.', 'Next', 35),
('contact', 'step_2_title', 'Step 2 title', 'text', 'I give you an honest read', 'Next', 36),
('contact', 'step_2_body', 'Step 2 body', 'textarea', 'I''ll tell you what I think is actually going on — including the parts that aren''t flattering — and whether strategy, creative, SEO or some mix of them is where your money should go first. If I''m not the right person for it, you''ll hear that here.', 'Next', 37),
('contact', 'step_3_title', 'Step 3 title', 'text', 'A plan you can see', 'Next', 38),
('contact', 'step_3_body', 'Step 3 body', 'textarea', 'If we''re a fit, I put together a clear plan: what we''re doing, in what order, and what we''re spending where. Nothing hidden behind jargon.', 'Next', 39),
('contact', 'step_4_title', 'Step 4 title', 'text', 'Make it, test it, scale what works', 'Next', 40),
('contact', 'step_4_body', 'Step 4 body', 'textarea', 'We build the creative and set things live, start small, and let the evidence decide what to scale. I''ll flag early if something isn''t working instead of defending it — correcting course fast is cheaper than dressing it up.', 'Next', 41),
('contact', 'faq_label', 'Section label', 'text', 'Straight answers', 'FAQ', 50),
('contact', 'faq_heading', 'Heading', 'text', 'A couple of honest answers', 'FAQ', 51),
('contact', 'faq_1_q', 'Question 1', 'text', 'Is the first call just a sales pitch in disguise?', 'FAQ', 53),
('contact', 'faq_1_a', 'Answer 1', 'textarea', 'No. It''s there to figure out whether I can actually help your business. If I can''t see a real result in it for you, I''ll say so directly rather than take the work.', 'FAQ', 54),
('contact', 'faq_2_q', 'Question 2', 'text', 'Do you only take big brands?', 'FAQ', 55),
('contact', 'faq_2_a', 'Answer 2', 'textarea', 'No. I keep a small roster and work with both new brands on tight budgets and established ones. For smaller brands, the whole approach is testing before scaling so nothing gets wasted.', 'FAQ', 56),
('contact', 'cta_eyebrow', 'Eyebrow', 'text', 'Let''s work together', 'Closing CTA', 70),
('contact', 'cta_heading', 'Heading', 'text', 'Strategy and creative from the same place', 'Closing CTA', 71),
('contact', 'cta_lede', 'Body', 'textarea', 'Grounded in what actually works rather than what sounds good on a deck. Reach out and tell me where you''re headed.', 'Closing CTA', 72),
('contact', 'cta_primary', 'Primary button label', 'text', 'Send a message', 'Closing CTA', 73);
